-- Tables
create table if not exists homepage_services (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  icon text,
  image_url text,
  created_at timestamp default now()
);

create table if not exists homepage_stats (
  id bigint generated by default as identity primary key,
  label text not null,
  value text not null,
  icon text
);

create table if not exists homepage_why_choose (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  icon text
);

create table if not exists homepage_cta (
  id bigint generated by default as identity primary key,
  heading text,
  subtext text,
  button_text text,
  button_link text
);

create table if not exists service_categories (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  icon text
);

create table if not exists detailed_services (
  id bigint generated by default as identity primary key,
  category_id bigint references service_categories(id) on delete set null,
  title text not null,
  description text,
  icon text,
  feature_1 text,
  feature_2 text,
  feature_3 text,
  created_at timestamp default now()
);

create table if not exists pricing_packages (
  id bigint generated by default as identity primary key,
  name text not null,
  price text not null,
  period text not null,
  description text,
  is_popular boolean default false
);

create table if not exists footer_contact (
  id bigint generated by default as identity primary key,
  address text,
  phone text,
  email text
);

-- Seed data
insert into homepage_services (title, description, icon, image_url) values
('AC/DC Motor Rewinding',
 'Precision rewinding for all sizes using class H insulation. We restore motors to OEM specifications or better.',
 'ri-settings-3-line',
 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?q=80&w=800&auto=format&fit=crop'),
('Industrial Pump Repair',
 'Complete refurbishment of submersible, centrifugal, and pressure pumps including seal replacement.',
 'ri-drop-line',
 'https://images.unsplash.com/photo-1565514020175-0c2235d8180e?q=80&w=800&auto=format&fit=crop'),
('Transformer Services',
 'Testing, oil analysis, and rewinding for distribution transformers.',
 'ri-flashlight-line',
 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=800&auto=format&fit=crop'),
('Generator Maintenance',
 'Stator and rotor rewinding, exciter repair, and testing for standby units.',
 'ri-battery-charge-line',
 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?q=80&w=800&auto=format&fit=crop'),
('Vibration Analysis',
 'Predictive maintenance using advanced vibration analysis and alignment.',
 'ri-pulse-line',
 'https://images.unsplash.com/photo-1531297461136-82af022f5b7a?q=80&w=800&auto=format&fit=crop'),
('Control Panel Design',
 'Custom VFD and starter panel building and automation retrofits.',
 'ri-dashboard-line',
 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?q=80&w=800&auto=format&fit=crop');

insert into homepage_stats (label, value, icon) values
('Emergency Service', '24/7', 'ri-time-line'),
('Motors Repaired', '5k+', 'ri-tools-line'),
('Years Experience', '20+', 'ri-shield-check-line'),
('Call Now', '+91 98765 43210', 'ri-phone-line');

insert into homepage_why_choose (title, description, icon) values
('Rapid Turnaround',
 'We understand downtime costs money. Our efficient process ensures your equipment is back online faster.',
 'ri-timer-flash-line'),
('Certified Technicians',
 'Our team consists of experienced professionals with years of hands-on field work.',
 'ri-verified-badge-line'),
('1-Year Warranty',
 'We stand behind our work with a 12‑month warranty on all rewinds and major repairs.',
 'ri-history-line');

insert into homepage_cta (heading, subtext, button_text, button_link) values
('Ready to Optimize Your Equipment?',
 'Get a free quote or schedule a repair visit today.',
 'Contact Us Now',
 '#contact');

insert into service_categories (name, description, icon) values
('Motor Rewinding',
 'Precision rewinding services for all types of AC/DC motors, pumps, and industrial machinery.',
 'ri-settings-3-line'),
('Fan Repair Services',
 'Repair and maintenance for ceiling, table, and exhaust fans including coil winding and bearing replacement.',
 'ri-windy-line'),
('Electrical Repair',
 'Diagnosis and repair for home appliances, circuit boards, and wiring installations.',
 'ri-flashlight-line');

-- detailed_services: a few examples per category
insert into detailed_services (category_id, title, description, icon, feature_1, feature_2) values
(1, 'Submersible Pump Motor Rewinding',
 'Waterproof rewinding for submersible pumps using high‑grade insulated copper.',
 'ri-drop-line',
 'Water‑resistant insulation', 'High‑temperature varnish'),
(1, 'Pressure Pump Motor Repair',
 'Restoring pressure capabilities for booster pumps with precision rewinding.',
 'ri-speed-up-line',
 'Seal replacement', 'Pressure testing'),
(2, 'Ceiling Fan Repair',
 'Fixing wobbly, noisy, or slow ceiling fans with capacitor and bearing service.',
 'ri-contrast-drop-2-line',
 'Balancing', 'Bearing lubrication'),
(3, 'Wiring & Installation',
 'Professional wiring for new machinery installation and control panel setup.',
 'ri-tools-line',
 'Follows safety standards', 'Load balancing');

insert into pricing_packages (name, price, period, description, is_popular) values
('Basic Service', '₹499', 'visit', 'For minor repairs and checkups.', false),
('Standard Repair', '₹1,999', 'fix', 'Complete motor rewinding & repair.', true),
('Industrial AMC', '₹9,999', 'month', 'Annual contract for factories.', false);

insert into footer_contact (address, phone, email) values
('Your Shop Name, Main Road, Your City, India', '+91 98765 43210', 'support@rewindingpros.in');



create table if not exists works (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  image_url text,
  category text,
  created_at timestamp default now()
);

insert into works (title, description, image_url, category) values
('Motor Rewinding Project', 'Completed full rewinding of 5HP induction motor with class H insulation.', 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?q=80&w=800', 'Motor'),
('Pump Repair Job', 'Repaired submersible pump with seal replacement and waterproof varnish.', 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?q=80&w=800', 'Pump'),
('Ceiling Fan Overhaul', 'Replaced bearings and rewound copper coil for silent operation.', 'https://images.unsplash.com/photo-1520072959219-c595dc870360?q=80&w=800', 'Fan');



create table if not exists testimonials (
  id bigint generated by default as identity primary key,
  name text not null,
  message text not null,
  rating int default 5,
  avatar_url text,
  created_at timestamp default now()
);

insert into testimonials (name, message, rating, avatar_url) values
('Rajesh Patel', 'Very fast and professional service. My motor works like new again!', 5, 'https://randomuser.me/api/portraits/men/32.jpg'),
('Meena Shah', 'Affordable and reliable. They fixed my water pump perfectly.', 5, 'https://randomuser.me/api/portraits/women/45.jpg'),
('Deepak Vora', 'Great experience. They rewound my industrial motor within 24 hours.', 4, 'https://randomuser.me/api/portraits/men/12.jpg');


create table if not exists faq (
  id bigint generated by default as identity primary key,
  question text not null,
  answer text not null,
  created_at timestamp default now()
);

insert into faq (question, answer) values
('How long does motor rewinding take?', 'Most rewinding jobs take 24-48 hours depending on motor size.'),
('Do you provide on-site repair?', 'Yes, we provide on-site inspection and repair for pumps and motors.'),
('What warranty do you offer?', 'We provide 6 to 12 months warranty based on the service.'),
('Do you repair submersible pumps?', 'Yes, complete sealing, rewinding, and testing for all pump types.');
